# -*- coding: utf-8 -*-
"""PelliRobson_CAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6RZWsn6c7hLXmWCVwFaxjLE4hPYLmY_
"""

import random
import numpy as np

# Define the initial contrast level and the decrement per triplet
initial_contrast = 1.0  # 100%
log_decrement = 0.15  # Log unit decrement per triplet

# Calculate contrast levels for 14 triplets
contrast_levels = [initial_contrast * (10 ** (-log_decrement * i)) for i in range(14)]
log_contrast_levels = [round(np.log10(c), 2) for c in contrast_levels]

# Syllabics optotypes
optotypes = list("ᐱᑎᑭᒧᒋᒥᑯᔨᔨ")
random.shuffle(optotypes)

# Generate LaTeX table rows
rows = []
for row_index in range(7):  # Loop to create 7 rows
    # First triplet
    group1_index = row_index * 2
    group1_contrast = contrast_levels[group1_index]
    group1_log_contrast = log_contrast_levels[group1_index]
    group1_gray = round(1 - group1_contrast, 2)
    triplet1 = "".join(random.choices(optotypes, k=3))

    # Second triplet
    group2_index = group1_index + 1
    group2_contrast = contrast_levels[group2_index]
    group2_log_contrast = log_contrast_levels[group2_index]
    group2_gray = round(1 - group2_contrast, 2)
    triplet2 = "".join(random.choices(optotypes, k=3))

    # Add row with both contrast levels in the first column
    rows.append(
        rf"""\noalign{{\vskip 50pt}} \textbf{{{int(group1_contrast * 100)} / {group1_log_contrast} \& {int(group2_contrast * 100)} / {group2_log_contrast}}} & \contrast{{{group1_gray}}}{{\optotype{{\optotypesize}}{{{triplet1}}}}} & \contrast{{{group2_gray}}}{{\optotype{{\optotypesize}}{{{triplet2}}}}} \\"""
    )

# Combine rows into the TeX table
tex_content = "\n".join(rows)
print(tex_content)